ALTER TABLE "companies" ADD COLUMN "roa" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "roe" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "current_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "quick_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "cash_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "debt_to_equity" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "debt_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "equity_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "gross_profit_margin" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "net_profit_margin" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "operating_margin" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "asset_turnover" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "interest_coverage" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "working_capital" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "price_to_sales" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "price_to_cash_flow" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "enterprise_value" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "ev_to_ebitda" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "beta" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "payout_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "retention_ratio" real;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "financial_data" jsonb;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "ratios_data" jsonb;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "payouts_data" jsonb;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "announcements" jsonb;