-- Add missing columns to stocks table to fix bid_price errors
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS bid_price REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS bid_volume INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS ask_price REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS ask_volume INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS high_52_week REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS low_52_week REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS market_cap REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS shares REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS free_float REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS upper_cap REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS lower_cap REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS haircut REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS beta REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS listed_in JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pivot_points JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS returns JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_trade_date TEXT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS type INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS status INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_day_close_volume INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS etf JSONB;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS xb BOOLEAN;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS xd BOOLEAN;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS xr BOOLEAN;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS sd BOOLEAN;

-- Also add missing WebSocket-specific fields for CapitalStake data
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_trade_time TEXT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_trade_price REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_trade_volume INTEGER;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS value REAL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS trades INTEGER;